############################################################
#
# Home Assistant Main Configuration File
#
############################################################

homeassistant:
  name: Home
  latitude: !secret latitude 
  longitude: !secret longitude 
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
#  customize: !include includes/customise.yaml
#  packages:
#    cctv: !include includes/packages/CCTV.yaml

http:
  base_url: !secret base_url
  api_password: !secret http_password
#  server_host: !secret server_host
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.100.0/24
    - 192.168.200.0/24
    - 2001:DB8:ABCD::/48
  ip_ban_enabled: True
  login_attempts_threshold: 5
    
history:

updater:
  reporting: no

frontend:

discovery:

#influxdb:
#  host: !secret influxdb_host
#  database: !secret influxdb_database
#  username: !secret influxdb_username
#  password: !secret influxdb_password

#recorder:
#  db_url: !secret mysql_path
#  purge_days: 3

sun:
  elevation: 210

# View all events in a logbook
logbook:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

############################################################
#
# Components
#
############################################################

#light:
#  platform: hue
#  host: !secret hue_ip
#  allow_unreachable: true

#nest:
#  client_id: !secret nest_client_id
#  client_secret: !secret nest_client_secret

#mqtt:
#  broker: !secret mqtt_ip
#  port: !secret mqtt_port
#  client_id: !secret mqtt_client_id
#  keepalive: 60
#  username: !secret mqtt_username
#  password: !secret mqtt_password

#google:
#  client_id: !secret google_calendar_client_id
#  client_secret: !secret google_calendar_client_secret

#zwave:
#  usb_path: /zwaveusbstick

sensor:
  - platform: netatmo
    station: rNET_Weather
    modules:
      module_name1:
        - temperature
      module_name2:
        - temperature
        - battery_vp

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
#  discovery: false

#apcupsd:
#  host: !secret apcupsd_host
#  port: !secret apcupsd_port

#remote:
#  - platform: harmony
#    name: !secret harmony_name
#    host: !secret harmony_host

tts:
  - platform: google

###########################################################
#
# Includes
#
############################################################

# Single Files

#binary_sensor: !include includes/binary_sensors.yaml
#camera: !include includes/cameras.yaml
#climate: !include includes/climate.yaml
#device_tracker: !include includes/device_trackers.yaml
#input_boolean: !include includes/input_boolean.yaml
#input_select: !include includes/input_select.yaml
#logger: !include includes/logger.yaml
#media_player: !include includes/media_players.yaml
#notify: !include includes/notify.yaml
#scene: !include includes/scenes.yaml
##switch: !include includes/switch.yaml
#weblink: !include includes/weblink.yaml

# Merge List

#automation: !include_dir_merge_list includes/automation
#sensor: !include_dir_merge_list includes/sensors
#shell_command: !include_dir_merge_named includes/shell_command
#zone: !include_dir_merge_list includes/zone

# Merge Named

#group: !include_dir_merge_named includes/group
#script: !include_dir_merge_named includes/scripts

