############################################################
#
# Home Assistant Main Configuration File
#
############################################################

homeassistant:
  name: Home
  latitude: !secret latitude 
  longitude: !secret longitude 
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include includes/customize.yaml
  # Customize entities matching a pattern
  customize_glob:
    "switch.zone_*":
      icon: mdi:water-pump

http:
  base_url: !secret base_url
  api_password: !secret http_password
#  server_host: !secret server_host
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 172.20.0.0/24
    - 192.168.100.0/24
    - 192.168.200.0/24
    - 2001:DB8:ABCD::/48

history:

# Optional, allows Home Assistant developers to focus on popular components.
updater:
  reporting: no
  # include_used_components: true

frontend:

discovery:
  ignore:
    - harmony

sun:
  elevation: 210

# View all events in a logbook
logbook:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

############################################################
#
# Components
#
############################################################

light:
  - platform: lifx
#    broadcast: !include lifx_broadcast

#google:
#  client_id: !secret google_calendar_client_id
#  client_secret: !secret google_calendar_client_secret

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
#  discovery: false

remote:
  - platform: harmony
    name: !secret harmony_name
    host: !secret harmony_host

tts:
  - platform: google

###########################################################
#
# Includes
#
############################################################

# Single Files

camera: !include includes/cameras.yaml
vera:   !include includes/vera.yaml
switch: !include includes/switch.yaml #includes Rachio config
media_player: !include includes/media_players.yaml
google_assistant: !include includes/google_assistant.yaml
hue: !include includes/philips_hue.yaml

# Group Merge Directory

group: !include_dir_merge_named group/
scene: !include_dir_merge_named scenes/


# -----
#input_select: !include includes/input_select.yaml
#notify: !include includes/notify.yaml
#scene: !include includes/scenes.yaml
#weblink: !include includes/weblink.yaml

# Merge List
#automation: !include_dir_merge_list includes/automation
#sensor: !include_dir_merge_list includes/sensors
#shell_command: !include_dir_merge_named includes/shell_command
#zone: !include_dir_merge_list includes/zone

# Merge Named
#group: !include group/irrigation.yaml
#group: !include group/lights.yaml

#script: !include_dir_merge_named includes/scripts
