############################################################
#
# Home Assistant Media Players
#
############################################################

- platform: plex
  scan_interval: 3

- platform: samsungtv
  host: !secret samsung_tv_ip

- platform: cast
  host: !secret cast_ip_1

- platform: cast
  host: !secret cast_ip_2