############################################################
#
# Home Assistant Rachio Configuration
#
############################################################

- platform:     rachio
  name:         rachio
  icon:         mdi:water-pump
  access_token: !secret rachio_api_key
